
notifications:
  email: false

jobs:
  include:
  - name: "manylinux1"
    sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PLAT=manylinux1_x86_64
  - name: "manylinux2010"
    sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64 PLAT=manylinux2010_x86_64

install:
- docker pull $DOCKER_IMAGE

script:
- docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-linux-wheels.sh
- ls dist/

deploy:
  skip_cleanup: true
  provider: pypi
  distributions: bdist_wheel
  user: "__token__"
  password:
    secure: gFYi64fXgu8BkagnbxnmCh3PFlsLnuBXl/X9P6RMS3g5oaRlbVIQQqmmeOzsGkDUgqD4O5wF9wAND6wm54npA2d28zm5N0k0eU+DdKoUVoL1MGASwEYvNE5zTvC4XZEy36oBAGzHo9uuRWcDVSXDJWSIx5Iq5O2D88tMRitXz2TNjDvRv1QD9fsjE5TpxOilvT+fZiFGrB9FbXShCOZLvF2MZN1dLPqJBUMPpZyPuhfkqPhFMqdbRK0c9W8C9URI/KuwcM7dFFJm93GvDZiazv12BO9ekrWAExJvvhvMUM5O5gINs8Wh/Wxq9FcmakcUKWMyCWmEEOAiyQubNQxnkctTa3PlX0Vs8pwqqEgsaJmF+KE1aFnkacOvn6rDTVT6+Pd2/FWntl6pWWC01IVMrnKFZYfbPX3Yk2ppUpikhhxmaAQO3B51BeQn6Xf7Yak6flKur18EdTjjrNL2Mt1x7BJ1SycsU4uJDv0+htl9AQYdSts6CKYVoYQe00hXRYmb55MCN/3hJ8KiApbpb7h3fNsyK/MNmLKc/On+MmDdLKJ4B260lIN+Uaj6z1ZMQ+hSBx7oMjMt+HUE/IW/0PKRS+WDAI6dJ+5uzjMVkD/rQavPStcDQFF3w6suMz78RSS8NC2ghX5egxFcL+dh4hRaEGyCrMKIsav3hfTVvXdOL5A=
  on:
    tags: true
    branch:
      - master
      - /v?(\d+\.)?(\d+\.)?(\*|\d+)$/
